### PR TITLE
Custom check box

### PR DESCRIPTION
**Pull request by fvitalini**
Includes css customisation of checkboxes.

Happy if someone else would like to spend some time in prettifying the outlook.

### CODE REVIEW

**Review by riccardoporreca — CHANGES_REQUESTED** [review]
The pull requests also includes changes to files outside the actual `BFE_RShiny/flamingo` app code (under `build/` and `src/`), which seem to come from the `master` branch and do not belong (yet) to `workflowRestructuring`, at least not as part of merging `customCheckBox`.

Only the changes to flamingo-tweaks.css should be merged from `customCheckBox`, or the changes from master merged directly into `workflowRestructuring` first.

**Comment by fvitalini** [comment]
Corrected merging the master changes to workflowRestructuring as a separate commit (it should have been done before).

**Review by riccardoporreca — APPROVED** [review]

**Comment by riccardoporreca** [comment]
Something can still be improved on the look of the custom check-boxes, like making them squares and making the check-mark a bit bigger.

**Comment by fvitalini** [comment]
Notice that the check-mark is an icon and its size is determined by the font size. the bigger the font-size the bigger the checkbox height, which is not a directly controlled parameter. The width of the checkbox has been manually adjusted to look square-ish, but it should be verified if it has a different outlook in different browsers

**Comment by riccardoporreca** [comment]
@fvitalini, I have played a little bit with CSS  under miraisolutions/miscellaneous@23a99ec620aee56a2ff3d339388025d50aa012b5.

I have simplified a the checkbox CSS and made use of a FontAwesome icon that renders better for the font size. I also made sure the boxes are square and introduced the usual round corners.
As for the radio buttons, I found a different approach which gives a look more consistent with the traditional buttons.

Below a screenshot of the result, you can double-check it and possibly bring it to Flamingo.

screenshot from 2018-10-10 19-07-24

**Comment by fvitalini** [comment]
@riccardoporreca there is a platform dependency for the new check-mark icons (or the version I have is not the same as the one for your screenshot). 
Here is how it looks in my mac (independently of the browser)
image

**Comment by riccardoporreca** [comment]
@fvitalini, same here trying on a Windows machine... It looks like the FontAwesome itself is not directly available on those systems but magically is if you have at list a `shiny::icon()`. On top of this, hex unicode character specifications must be used for portability.

I have fixed this in miraisolutions/miscellaneous@0c2835ed559fca12925403650c98a43aaefc2aa9

Note that on the Flamingo side we will be OK as we already use FontAwesome in CSS there.

**Comment by fvitalini** [comment]
@riccardoporreca  quite a mystery but it works. 
I have integrated your changes in flamingo_tweaks.css

**Review by nfarabullini — APPROVED** [review]

**Pull request merged**
