### PR TITLE
changed bsTooltip from shinyBS to bs_embed_tooltip from bsplus

### PR DESCRIPTION
**Pull request by nfarabullini**

### CODE REVIEW

**Review by fvitalini — CHANGES_REQUESTED** [review]
@nfarabullini a few issues that should be fixed before merging:
- no need to importFrom shinyBS bsTooltip in fileViewer_ui.R as the tooltips are in the submodule viewFiles.R
- Placement of tooltip for abuttondefineaccount and abuttonsysconf should be left
- in global remove or complete the list of libraries required by the package and currently commented out
- in pageStructure.R the tooltips of the buttons inside the dropdown are not working
- the style of some buttons is lost (e.g.: abuttongotorun, abuttondefineprogrammesingle, abuttondefineprogrammebatch, abuttonbrowseSBR, abuttonbrowseBBR, abuttonfilemngt)
- the tooltips of the dropdownbuttons look the same as the ones of shinyBS and quite different from the ones in bsplus. Remove " tooltip = tooltipOptions(title = landing_page$abuttonbrowse, placement = "right")," in dropdownButton and add a bs_embed_tooltip to the widget.
- building of the package is currently broken because programmeDefinitionSingle still uses shinyBS for tooltips. Either reintroduce shinyBS in the NAMESPACE or pull from restructureProgDefSingle (merging is very simple, only conflict is in viewFiles.R and you need to take the version in  restructureProgDefSingle to use the leaflet map).

**Comment by nfarabullini** [comment]
@fvitalini 

I think that something went wrong with the pull request because all of the tooltips work on my laptop (except of course for ProgrammeDefinitionSingle) and the changes that you requested were already made and committed (the only new thing that I removed is the " tooltip = tooltipOptions(title = landing_page$abuttonbrowse, placement = "right")," ). 

I have reintegrated shinyBS back into the NAMESPACE and tested, everything should work for you too now.

**Comment by fvitalini** [comment]
Sorry but these issues are still present.
 - remove importFrom bsplus bs_embed_tooltip in fileViewer_ui.R as the tooltips are in the submodule viewFiles.R
- Placement of tooltip for abuttondefineaccount and abuttonsysconf should be left
- in global remove (or complete) the list of libraries required by the package and currently commented out
- the style of some buttons is lost (e.g.: abuttongotorun, abuttondefineprogrammesingle, abuttondefineprogrammebatch, abuttonbrowseSBR, abuttonbrowseBBR, abuttonfilemngt)
- the tooltips of the dropdownbuttons should not be removed but replaced with the new tooltips. Now in browse it is removed and in Process the old ones are still present

**Comment by nfarabullini** [comment]
tooltips are now consistent throughout the UI.

Style of actionButtons has problems due to #89 and will be addressed / fixed separately.

**Review by fvitalini — APPROVED** [review]

**Review by RolandASc — APPROVED** [review]

**Pull request merged**
